### ISSUE TITLE
Chrome 71 autojoin not working anymore

### ISSUE THREAD

**Issue by Antipika** [ypinskiy/GBF-Raiders#38]
When pressing the "Join Now" button on GBF Raiders, raids aren't automatically joined anymore (even if the API box is ticked). The following error appears on the console:

```
Error sending join command to Viramate: Cannot read property 'contentWindow' of null TypeError: Cannot read property 'contentWindow' of null
    at SendJoinCommand (main.js:773)
    at HTMLButtonElement.<anonymous> (raids.js:283)
```

I did roll back to Chrome 70, no problem. It doesn't seems to be a Viramate issue since joining through api_test.html is working fine as well.

**Comment by bosiddon** [comment]
`<iframe id="viramate-api" src="chrome-extension://fgpokpknehglcioijejfeebigdnbnokj/content/api.html" width="1" height="1"><p>Your browser does not support iframes.</p></iframe>`

Looks like the issue is that this iframe used to load right above the welcome div, but for some reason it doesn't load in chrome 71

**Comment by ashemedai** [comment]
FWIW @ypinskiy, I cannot reproduce the above with Chrome 71.0.3578.98.

**Comment by ypinskiy** [comment]
Fixed in commit 49400c19bcfe4a72c0fa9c5aa2e01969481f3c4e

**Comment by Ningyoplug** [comment]
This is still happening to me on Chrome 71.0.3578.98, both on the regular gbfraiders website and the chrome extension. Autojoin won't work, it only lets me copy the ID.
I'm updating Chrome to version 72.0.3626.81 right now.
...Website not working in Chrome 72.0.3626.81 either. The chrome extension's autojoin works though.
The API box on Viramate is ticked.

**Comment by Antipika** [comment]
This should be re-opened, still having issue as of today, Chrome 72.0.3626.121

Chrome 70 still has no issue.

**Comment by ypinskiy** [comment]
@Antipika please make sure that the browser cache is cleared. Also, try the site in incognito mode to see if that works. The issue that caused this has been fixed as long as your browser has the correct version.

**Comment by Antipika** [comment]
Cleared cache and worked, sorry again about that :)
